// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bpglcfechtxoukhfnhim.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJwZ2xjZmVjaHR4b3VraGZuaGltIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjI1OTY1NDQsImV4cCI6MjA3ODE3MjU0NH0.aLI_CIFyzYAgkleG9HNJSBsh9ylhiwvM8ueWAPrn7do";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});